// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';
import 'package:proofmaster/app/domain/entities/material/learning_material.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'menu_item.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'menu_item.g.dart';

@freezed
class MenuItem with _$MenuItem {
  const factory MenuItem({
    required bool isSeparator,
    String? iconUrl,
    String? separatorText,
    LearningMaterial? learningMaterial,
  }) = _DashboardItem;

  factory MenuItem.fromJson(Map<String, Object?> json) =>
      _$MenuItemFromJson(json);
}
