// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';
import 'package:proofmaster/app/domain/entities/material/learning_material.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'dashboard_item.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'dashboard_item.g.dart';

@freezed
class DashboardItem with _$DashboardItem {
  const factory DashboardItem({
    required bool isSeparator,
    String? separatorText,
    LearningMaterial? learningMaterial,
  }) = _DashboardItem;

  factory DashboardItem.fromJson(Map<String, Object?> json) =>
      _$DashboardItemFromJson(json);
}
